name: my_first_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:

  buttons_tabbar: ^1.3.15
  contained_tab_bar_view: ^0.8.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  path_provider: ^2.1.5
  persistent_shopping_cart: ^0.0.7
  simple_animation_progress_bar: ^1.8.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  step_progress_indicator: ^1.0.2
  hive:
  hive_flutter:
  change_app_package_name: ^1.4.0
  rename: ^2.1.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/Splash.png
    - assets/low_battery.png
    - assets/home.jpg
    - assets/icons/
    - assets/coffee.jpg
    - assets/mocha.jpg
    - assets/mocha1.jpg
    - assets/mocha2.jpg
    - assets/espresso.jpg
    - assets/latte.jpg
    - assets/capuccino.jpg
    - assets/pistachio_latte.jpg
    - assets/vanilla_latte.jpg
    - assets/spanish_latte.jpg
    - assets/empty_cart.jpg
    - assets/americano.jpg
    - assets/profilepic.jpg
    - assets/no_favourites.png
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf


