// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjbHVA3TBpDqCgmfFYTAAyADiume6ziqM',
    appId: '1:746185996834:web:c7839638a86c58ff5d287b',
    messagingSenderId: '746185996834',
    projectId: 'coffee-shop-app-6550a',
    authDomain: 'coffee-shop-app-6550a.firebaseapp.com',
    storageBucket: 'coffee-shop-app-6550a.firebasestorage.app',
    measurementId: 'G-2VG2QY1RK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiLa4O68sywGDXUUjDQrM8EyX1bqh2ltM',
    appId: '1:746185996834:android:b0d260c072707ef65d287b',
    messagingSenderId: '746185996834',
    projectId: 'coffee-shop-app-6550a',
    storageBucket: 'coffee-shop-app-6550a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvFKQTKNF-O1AsifOBZDjl31GWRmx6svo',
    appId: '1:746185996834:ios:168b8fd08a83d3085d287b',
    messagingSenderId: '746185996834',
    projectId: 'coffee-shop-app-6550a',
    storageBucket: 'coffee-shop-app-6550a.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvFKQTKNF-O1AsifOBZDjl31GWRmx6svo',
    appId: '1:746185996834:ios:168b8fd08a83d3085d287b',
    messagingSenderId: '746185996834',
    projectId: 'coffee-shop-app-6550a',
    storageBucket: 'coffee-shop-app-6550a.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjbHVA3TBpDqCgmfFYTAAyADiume6ziqM',
    appId: '1:746185996834:web:1b024e11e795ab345d287b',
    messagingSenderId: '746185996834',
    projectId: 'coffee-shop-app-6550a',
    authDomain: 'coffee-shop-app-6550a.firebaseapp.com',
    storageBucket: 'coffee-shop-app-6550a.firebasestorage.app',
    measurementId: 'G-C6K4RKCSJW',
  );
}
